// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: chitchat/grpc/proto/chitchat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_chitchat_proto_rawDescGZIP(), []int{0}
}

type JoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_chitchat_proto_rawDescGZIP(), []int{1}
}

func (x *JoinReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type LeaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveReq) Reset() {
	*x = LeaveReq{}
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveReq) ProtoMessage() {}

func (x *LeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveReq.ProtoReflect.Descriptor instead.
func (*LeaveReq) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_chitchat_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type PublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_chitchat_proto_rawDescGZIP(), []int{3}
}

func (x *PublishReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PublishReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_chitchat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_chitchat_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BroadcastMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BroadcastMessage) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

var File_chitchat_grpc_proto_chitchat_proto protoreflect.FileDescriptor

const file_chitchat_grpc_proto_chitchat_proto_rawDesc = "" +
	"\n" +
	"\"chitchat/grpc/proto/chitchat.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"&\n" +
	"\aJoinReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"'\n" +
	"\bLeaveReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"C\n" +
	"\n" +
	"PublishReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"l\n" +
	"\x10BroadcastMessage\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x03R\vlogicalTime2\x91\x01\n" +
	"\bChitchat\x121\n" +
	"\x04Join\x12\x0e.proto.JoinReq\x1a\x17.proto.BroadcastMessage0\x01\x12*\n" +
	"\aPublish\x12\x11.proto.PublishReq\x1a\f.proto.Empty\x12&\n" +
	"\x05Leave\x12\x0f.proto.LeaveReq\x1a\f.proto.EmptyB\x15Z\x13chitchat/grpc/protob\x06proto3"

var (
	file_chitchat_grpc_proto_chitchat_proto_rawDescOnce sync.Once
	file_chitchat_grpc_proto_chitchat_proto_rawDescData []byte
)

func file_chitchat_grpc_proto_chitchat_proto_rawDescGZIP() []byte {
	file_chitchat_grpc_proto_chitchat_proto_rawDescOnce.Do(func() {
		file_chitchat_grpc_proto_chitchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chitchat_grpc_proto_chitchat_proto_rawDesc), len(file_chitchat_grpc_proto_chitchat_proto_rawDesc)))
	})
	return file_chitchat_grpc_proto_chitchat_proto_rawDescData
}

var file_chitchat_grpc_proto_chitchat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chitchat_grpc_proto_chitchat_proto_goTypes = []any{
	(*Empty)(nil),            // 0: proto.Empty
	(*JoinReq)(nil),          // 1: proto.JoinReq
	(*LeaveReq)(nil),         // 2: proto.LeaveReq
	(*PublishReq)(nil),       // 3: proto.PublishReq
	(*BroadcastMessage)(nil), // 4: proto.BroadcastMessage
}
var file_chitchat_grpc_proto_chitchat_proto_depIdxs = []int32{
	1, // 0: proto.Chitchat.Join:input_type -> proto.JoinReq
	3, // 1: proto.Chitchat.Publish:input_type -> proto.PublishReq
	2, // 2: proto.Chitchat.Leave:input_type -> proto.LeaveReq
	4, // 3: proto.Chitchat.Join:output_type -> proto.BroadcastMessage
	0, // 4: proto.Chitchat.Publish:output_type -> proto.Empty
	0, // 5: proto.Chitchat.Leave:output_type -> proto.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chitchat_grpc_proto_chitchat_proto_init() }
func file_chitchat_grpc_proto_chitchat_proto_init() {
	if File_chitchat_grpc_proto_chitchat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chitchat_grpc_proto_chitchat_proto_rawDesc), len(file_chitchat_grpc_proto_chitchat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chitchat_grpc_proto_chitchat_proto_goTypes,
		DependencyIndexes: file_chitchat_grpc_proto_chitchat_proto_depIdxs,
		MessageInfos:      file_chitchat_grpc_proto_chitchat_proto_msgTypes,
	}.Build()
	File_chitchat_grpc_proto_chitchat_proto = out.File
	file_chitchat_grpc_proto_chitchat_proto_goTypes = nil
	file_chitchat_grpc_proto_chitchat_proto_depIdxs = nil
}
