// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: grpc/proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimeKeeper_GetTime_FullMethodName = "/proto.TimeKeeper/GetTime"
)

// TimeKeeperClient is the client API for TimeKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeKeeperClient interface {
	GetTime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TimeResponse, error)
}

type timeKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeKeeperClient(cc grpc.ClientConnInterface) TimeKeeperClient {
	return &timeKeeperClient{cc}
}

func (c *timeKeeperClient) GetTime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeResponse)
	err := c.cc.Invoke(ctx, TimeKeeper_GetTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeKeeperServer is the server API for TimeKeeper service.
// All implementations must embed UnimplementedTimeKeeperServer
// for forward compatibility.
type TimeKeeperServer interface {
	GetTime(context.Context, *Empty) (*TimeResponse, error)
	mustEmbedUnimplementedTimeKeeperServer()
}

// UnimplementedTimeKeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeKeeperServer struct{}

func (UnimplementedTimeKeeperServer) GetTime(context.Context, *Empty) (*TimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedTimeKeeperServer) mustEmbedUnimplementedTimeKeeperServer() {}
func (UnimplementedTimeKeeperServer) testEmbeddedByValue()                    {}

// UnsafeTimeKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeKeeperServer will
// result in compilation errors.
type UnsafeTimeKeeperServer interface {
	mustEmbedUnimplementedTimeKeeperServer()
}

func RegisterTimeKeeperServer(s grpc.ServiceRegistrar, srv TimeKeeperServer) {
	// If the following call panics, it indicates UnimplementedTimeKeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeKeeper_ServiceDesc, srv)
}

func _TimeKeeper_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeKeeperServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeKeeper_GetTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeKeeperServer).GetTime(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeKeeper_ServiceDesc is the grpc.ServiceDesc for TimeKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TimeKeeper",
	HandlerType: (*TimeKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTime",
			Handler:    _TimeKeeper_GetTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/proto.proto",
}
